development:
  redis_master:
    host: localhost
    port: 6379
    db: 0
  redis_slave:
    host: localhost
    port: 6379
    db: 0
  dev_email: 'alumnigtbit@gmail.com'

production:
  redis_master:
    host: localhost
    port: 6379
    db: 0
  redis_slave:
    host: localhost
    port: 6379
    db: 0
  dev_email: 'alumnigtbit@gmail.com'
