development:
  redis_master:
    host: localhost
    port: 6379
    db: 0
  redis_slave:
    host: localhost
    port: 6379
    db: 0

production:
  redis_master:
    host: localhost
    port: 6379
    db: 0
  redis_slave:
    host: localhost
    port: 6379
    db: 0
