# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: gan_dev
  username: "root"
  password: "root"

development:
  <<: *default

staging:
  <<: *default
  database: gan_staging

test:
  <<: *default
  database: gan_test

production:
  <<: *default
  database: gan_prod
  username: "gan"
  password: "ganrootpassword"
